# Generated by Django 6.0.3 on 2026-06-30 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('properties', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='property',
            name='latitude',
        ),
        migrations.RemoveField(
            model_name='property',
            name='longitude',
        ),
        migrations.AddField(
            model_name='property',
            name='google_map_link',
            field=models.URLField(blank=True, null=True, verbose_name='Google Maps Link'),
        ),
    ]
